// user constants
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_LOAD_REQUEST = "USER_LOAD_REQUEST";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";

export const USER_APPLY_JOB_REQUEST = 'USER_APPLY_JOB_REQUEST'
export const USER_APPLY_JOB_SUCCESS = 'USER_APPLY_JOB_SUCCESS'
export const USER_APPLY_JOB_FAIL = 'USER_APPLY_JOB_FAIL'

export const USER_UPLOAD_RESUME_REQUEST = 'USER_UPLOAD_RESUME_REQUEST'
export const USER_UPLOAD_RESUME_SUCCESS = 'USER_UPLOAD_RESUME_SUCCESS'
export const USER_UPLOAD_RESUME_FAIL = 'USER_UPLOAD_RESUME_FAIL'

// job constants
export const DELETE_JOB_REQUEST = 'DELETE_JOB_REQUEST'
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS'
export const DELETE_JOB_FAIL = 'DELETE_JOB_FAIL'

export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL'

export const JOBS_REQUEST = 'JOBS_REQUEST'
export const JOBS_SUCCESS = 'JOBS_SUCCESS'
export const JOBS_FAIL = 'JOBS_FAIL'

export const JOB_REQUEST = 'JOB_REQUEST'
export const JOB_SUCCESS = 'JOB_SUCCESS'
export const JOB_FAIL = 'JOB_FAIL'











